name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    env:
      KMD_BIN: Komodo/bin/Debug/net6.0/Komodo
      TESTS_DIR: tests/
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install termcolor
      - run: dotnet build
      - run: ls
      - run: python test.py $KMD_BIN $TESTS_DIR
